### ISSUE TITLE
Installation issues - invalid escape sequence

### ISSUE THREAD

**Issue by karenhn** [WatsonLab/KOunt#6] opened 2024-09-27 14:03 UTC
Hi, I'd like to use your package but I'm having issues with installation. I've followed all the steps until: 

`snakemake --use-conda --conda-create-envs-only --cores 1`

But I get the following error messages: 

```
/scratch/karenhn/KOunt/Snakefile:203: SyntaxWarning: invalid escape sequence '\/                                                     '
  filtered_gff=f'{outdir}Prodigal_Outputs/filtered_gffs/{{id}}/{{id}}.gff'
/scratch/karenhn/KOunt/Snakefile:219: SyntaxWarning: invalid escape sequence '\/                                                                  '
  rule bwa:
/scratch/karenhn/KOunt/Snakefile:680: SyntaxWarning: invalid escape sequence '\*                                                                  '
  touch {output}
/scratch/karenhn/KOunt/Snakefile:703: SyntaxWarning: invalid escape sequence '\*                                                                  '
  touch=f"{outdir}Touch/nohit_fa_{{id}}"
/scratch/karenhn/KOunt/Snakefile:748: SyntaxWarning: invalid escape sequence '\*                                                                  '
  '''
/scratch/karenhn/KOunt/Snakefile:767: SyntaxWarning: invalid escape sequence '\*                                                                  '
  of="6 qseqid sseqid pident qlen slen qstart qend sstart send evalue",
/scratch/karenhn/KOunt/Snakefile:807: SyntaxWarning: invalid escape sequence '\*                                                                  '
  raw=f"{outdir}diamond/NoHit_{{id}}_norna",
/scratch/karenhn/KOunt/Snakefile:825: SyntaxWarning: invalid escape sequence '\*                                                                  '
  shell:
FileNotFoundError in file /scratch/karenhn/KOunt/Snakefile, line 7:
[Errno 2] No such file or directory: 'test_fastqs/'
  File "/scratch/karenhn/KOunt/Snakefile", line 7, in <module>
```
I did try downloading the test_fastqs from the next step and rerunning the create envs code, but had the same issue. I'm fairly new to python etc, so could you tell me where I'm going wrong please?

**Comment by jmattock5** [comment] 2024-10-01 14:39
Hi, thank you for your feedback. I think these warnings are occurring since a recent Snakemake update. I've updated the installation instructions in the README to specify the snakemake and mamba versions to install. Please could you try and make the snakemake_mamba env again and see if that solves the problem?
Thanks,
Jenny

**Comment by karenhn** [comment] 2024-10-02 11:20
Thanks. I've tried again and it seemed to work better, but I now get a different error. Following
`snakemake --conda-create-envs-only --cores 1 --use-conda`
[my system said `Error: --use-conda must be set if --conda-prefix or --create-envs-only is set`]
I get these messages:

```
Traceback (most recent call last):
  File "/home/karenhn/.conda/envs/snakemake_mamba/lib/python3.11/weakref.py", line 666, in _exitfunc
    f()
  File "/home/karenhn/.conda/envs/snakemake_mamba/lib/python3.11/weakref.py", line 590, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karenhn/.conda/envs/snakemake_mamba/lib/python3.11/tempfile.py", line 933, in _cleanup
    cls._rmtree(name, ignore_errors=ignore_errors)
  File "/home/karenhn/.conda/envs/snakemake_mamba/lib/python3.11/tempfile.py", line 929, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "/home/karenhn/.conda/envs/snakemake_mamba/lib/python3.11/shutil.py", line 752, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/karenhn/.conda/envs/snakemake_mamba/lib/python3.11/shutil.py", line 672, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/home/karenhn/.conda/envs/snakemake_mamba/lib/python3.11/shutil.py", line 672, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/home/karenhn/.conda/envs/snakemake_mamba/lib/python3.11/shutil.py", line 672, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  [Previous line repeated 1 more time]
  File "/home/karenhn/.conda/envs/snakemake_mamba/lib/python3.11/shutil.py", line 683, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/home/karenhn/.conda/envs/snakemake_mamba/lib/python3.11/shutil.py", line 681, in _rmtree_safe_fd
    os.rmdir(entry.name, dir_fd=topfd)
OSError: [Errno 39] Directory not empty: 'envs'
```
Any help would be appreciated!
Karen

**Comment by jmattock5** [comment] 2024-10-03 16:56
Hi Karen,

Please could you try running the test installation steps and let me know what error messages you get for that?

Thanks,
Jenny

**Comment by karenhn** [comment] 2024-10-04 06:44
Hi Jenny, 

There's quite a lot of messages, so I'll just summarise! It starts with: 
```
rule trim:
    input: test_fastqs/ERR2027889_005/ERR2027889_005_R1.fastq.gz, test_fastqs/ERR2027889_005/ERR2027889_005_R2.fastq.gz
    output: out/Touch/trim_ERR2027889_005
    jobid: 1
    reason: Missing output files: out/Touch/trim_ERR2027889_005
    wildcards: id=ERR2027889_005
    resources: tmpdir=/tmp
```

And has this for outputs: BamDeal, Kofamscan, assemblies, Prodigal etc

And then after a page of these green messages, it has a list of counts and threads for the job stats and: 

```
Reasons:
    (check individual jobs above for details)
    input files updated by another job:
        abundance_matrix_annotate_with_mapping, abundance_results, all, bwa, cdhit, coverage, diamond_search, kallisto, kallisto_unmapped, kegg_fastas, kofamscan, kofamscan_results, megahit, mmseq_cluster_count, mmseq_keggs, mmseq_nohit, nohit_annotate_reads, nohit_fastas, nohit_fastq, prodigal, split_keggs, unmapped_reads
    missing output files:
        abundance_matrix_annotate_with_mapping, abundance_results, bamdeal, bwa, cdhit, coverage, diamond_search, kallisto, kallisto_unmapped, kegg_db, kegg_fastas, kofamscan, kofamscan_results, megahit, mmseq_cluster_count, mmseq_keggs, mmseq_nohit, nohit_annotate_reads, nohit_fastas, nohit_fastq, prodigal, split_keggs, trim, unmapped_reads

This was a dry-run (flag -n). The order of jobs does not reflect the order of execution.
```

There was no out directory created and no output files.

Karen

**Comment by jmattock5** [comment] 2024-10-04 16:21
Hi Karen,

This is the standard output we want to see after a dry run with Snakemake - it tells you which jobs will be run and what outputs will be created before you submit it. Please try running the same command but without the '-n' option to get it to actually run the pipeline.

Thanks,
Jenny

**Comment by karenhn** [comment] 2024-10-06 06:06
[2024-10-06T184627.149112.snakemake.log](https://github.com/user-attachments/files/17268353/2024-10-06T184627.149112.snakemake.log)

Hi Jenny, 

I've attached the log of all the error messages, but it finished with 
`
Exiting because a job execution failed. Look above for error message`
I did get an out directory with Kofamscan and trimmed, but nothing else.

Karen

**Comment by jmattock5** [comment] 2024-10-08 11:59
Hi Karen,
Ok, I would expect it to report that it was making the env before running the pipeline so I think Snakemake thinks the envs exist. Could you try removing the hidden snakemake folder `rm -r .snakemake` in your current directory and try again?
Jenny

**Comment by karenhn** [comment] 2024-10-09 02:16
Hi Jenny, 

Failed again :(
`Exiting because a job execution failed. Look above for error message`
[2024-10-09T120249.868195.snakemake.log](https://github.com/user-attachments/files/17300188/2024-10-09T120249.868195.snakemake.log)
I also tried adjusting the latency to 20 seconds, but either that wasn't enough or it wasn't the issue. 

Karen

**Comment by jmattock5** [comment] 2024-10-14 12:53
Hi Karen,

Just to double check, what OS are you trying to run KOunt on? I've just been trying to recreate your issues on a MacBook and discovered that one of the dependancies can only be run with Linux.

If you are on Linux then I think we should try making yet another snakemake env using this command:
```conda env create -n snakemake_mamba_old -f envs/snakemake_mamba.yaml```

Then activate this env, remove the old attempts and see if we can make the KOunt envs:
```
conda activate snakemake_mamba_old
rm -r .snakemake
rm -r out
snakemake --conda-create-envs-only --cores 1 --use-conda
```
Please can you send me all of the outputted text when you run this?
Thanks,
Jenny

**Comment by karenhn** [comment] 2024-10-15 01:51
Hi Jenny, 

I am on Linux (5.4.0.-189) with Ubuntu 20.04.6 LTS.

I got errors setting up the new environment about not having the right conda distribution:
`conda env create -n snakemake_mamba_old3 -f envs/snakemake_mamba.yaml` 
```
Installing pip dependencies: - Ran pip subprocess with arguments:
['/home/karenhn/.conda/envs/snakemake_mamba_old/bin/python', '-m', 'pip', 'install', '-U', '-r', '/scratch/karenhn/KOunt/envs/condaenv.ylft8l17.requirements.txt', '--exists-action=b']
Pip subprocess output:
Collecting aioeasywebdav==2.4.0
  Using cached aioeasywebdav-2.4.0-py3-none-any.whl (10 kB)
Collecting aiohttp==3.8.4
  Using cached aiohttp-3.8.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)
Collecting aiosignal==1.3.1
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting amply==0.1.5
  Using cached amply-0.1.5-py3-none-any.whl (16 kB)
Requirement already satisfied: appdirs==1.4.4 in /home/karenhn/.conda/envs/snakemake_mamba_old/lib/python3.10/site-packages (from -r /scratch/karenhn/KOunt/envs/condaenv.ylft8l17.requirements.txt (line 5)) (1.4.4)
Collecting async-timeout==4.0.2
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting attmap==0.13.2
  Using cached attmap-0.13.2-py3-none-any.whl (12 kB)
Collecting attrs==22.2.0
  Using cached attrs-22.2.0-py3-none-any.whl (60 kB)
Requirement already satisfied: backports-functools-lru-cache==1.6.4 in /home/karenhn/.conda/envs/snakemake_mamba_old/lib/python3.10/site-packages (from -r /scratch/karenhn/KOunt/envs/condaenv.ylft8l17.requirements.txt (line 9)) (1.6.4)
Collecting bcrypt==3.2.2
  Using cached bcrypt-3.2.2-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (62 kB)
Collecting boto3==1.26.77
  Using cached boto3-1.26.77-py3-none-any.whl (132 kB)
Collecting botocore==1.29.77
  Using cached botocore-1.29.77-py3-none-any.whl (10.4 MB)
Collecting brotlipy==0.7.0
  Using cached brotlipy-0.7.0-cp35-abi3-manylinux2010_x86_64.whl (1.1 MB)
Collecting cachetools==5.3.0
  Using cached cachetools-5.3.0-py3-none-any.whl (9.3 kB)
Collecting certifi==2022.12.7
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting cffi==1.15.1
  Using cached cffi-1.15.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (441 kB)

Pip subprocess error:
**ERROR: Could not find a version that satisfies the requirement conda==23.1.0 (from versions: 3.0.6, 3.5.0, 3.7.0, 3.17.0, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.0.7, 4.0.8, 4.0.9, 4.1.2, 4.1.6, 4.2.6, 4.2.7, 4.3.13, 4.3.16)
ERROR: No matching distribution found for conda==23.1.0**
failed
CondaEnvException: Pip failed
```
I have conda 23.11.0 within mambaforge. I tried changing the yaml file to reference either 23.11.0 or a version listed in the error message (4.3.16) but still got the same error. 

I tried the next steps anyway - and got these messages:
```
Traceback (most recent call last):
  File "/home/karenhn/.conda/envs/snakemake_mamba_old/lib/python3.10/site-packages/snakemake/__init__.py", line 760, in snakemake
    success = workflow.execute(
  File "/home/karenhn/.conda/envs/snakemake_mamba_old/lib/python3.10/site-packages/snakemake/workflow.py", line 1095, in execute
    raise e
  File "/home/karenhn/.conda/envs/snakemake_mamba_old/lib/python3.10/site-packages/snakemake/workflow.py", line 1091, in execute
    success = self.scheduler.schedule()
  File "/home/karenhn/.conda/envs/snakemake_mamba_old/lib/python3.10/site-packages/snakemake/scheduler.py", line 571, in schedule
    run = self.job_selector(needrun)
  File "/home/karenhn/.conda/envs/snakemake_mamba_old/lib/python3.10/site-packages/snakemake/scheduler.py", line 714, in job_selector_ilp
    from stopit import ThreadingTimeout as Timeout, TimeoutException
  File "/home/karenhn/.conda/envs/snakemake_mamba_old/lib/python3.10/site-packages/stopit/__init__.py", line 10, in <module>
    import pkg_resources
  File "/home/karenhn/.conda/envs/snakemake_mamba_old/lib/python3.10/site-packages/pkg_resources/__init__.py", line 95, in <module>
    from jaraco.text import drop_comment, join_continuation, yield_lines
  File "/home/karenhn/.conda/envs/snakemake_mamba_old/lib/python3.10/site-packages/setuptools/_vendor/jaraco/text/__init__.py", line 12, in <module>
    from jaraco.context import ExceptionTrap
  File "/home/karenhn/.conda/envs/snakemake_mamba_old/lib/python3.10/site-packages/setuptools/_vendor/jaraco/context.py", line 17, in <module>
    from backports import tarfile
ImportError: cannot import name 'tarfile' from 'backports' (/home/karenhn/.conda/envs/snakemake_mamba_old/lib/python3.10/site-packages/backports/__init__.py)
```
No out directory created.

**Comment by jmattock5** [comment] 2024-10-16 13:35
Hi Karen,

Please could to try to see if either of these solutions work?

Try making a new env, specifying python version 3.10.6, you may need to use another name:
```
conda create -n snakemake_mamba -c conda-forge -c bioconda mamba=1.0.0 python=3.10.6
conda activate snakemake_mamba
mamba install -c bioconda snakemake=7.22.0

rm -r .snakemake
rm -r out
snakemake --conda-create-envs-only --cores 1 --use-conda
```

Or make an env using this edited yml file (I couldn't upload with the right extension so you'll have to rename it)
[snakemake_mamba.txt](https://github.com/user-attachments/files/17396440/snakemake_mamba.txt)
```
mv snakemake_mamba.txt snakemake_mamba.yml
conda env create -n snakemake_mamba_old3 -f snakemake_mamba.yml
conda activate snakemake_mamba_old3
rm -r .snakemake
rm -r out
snakemake --conda-create-envs-only --cores 1 --use-conda
```

Thanks,
Jenny

**Comment by karenhn** [comment] 2024-10-17 01:31
Hi Jenny, 

The first option, making a new environment, was the same as the previous - it set up OK, but when I ran the `snakemake -k --ri` code it had the same issue with missing files. 
[2024-10-17T131808.549352.snakemake.log](https://github.com/user-attachments/files/17404834/2024-10-17T131808.549352.snakemake.log)

I couldn't get the second option to install. After `conda env create -n snakemake_mamba_old3 -f snakemake_mamba.yml` I got a heap of messages, ending with being unable to execute setup.py (see below).

By the way, thank you so much for helping me with this - I really appreciate it! (and I'm sorry my system doesn't work the way it should!)

Karen


```
Channels:
 - bioconda
 - conda-forge
 - biobakery
 - defaults
 - python2.7
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: | Ran pip subprocess with arguments:
['/home/karenhn/.conda/envs/snakemake_mamba_old3/bin/python', '-m', 'pip', 'install', '-U', '-r', '/scratch/karenhn/KOunt/condaenv.ij3k4slf.requirements.txt', '--exists-action=b']
Pip subprocess output:
Collecting aioeasywebdav==2.4.0
  Using cached aioeasywebdav-2.4.0-py3-none-any.whl (10 kB)
Collecting aiohttp==3.8.4
  Using cached aiohttp-3.8.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)
Collecting aiosignal==1.3.1
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting amply==0.1.5
  Using cached amply-0.1.5-py3-none-any.whl (16 kB)
Requirement already satisfied: appdirs==1.4.4 in /home/karenhn/.conda/envs/snakemake_mamba_old3/lib/python3.10/site-packages (from -r /scratch/karenhn/KOunt/condaenv.ij3k4slf.requirements.txt (line 5)) (1.4.4)
Collecting async-timeout==4.0.2
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting attmap==0.13.2
  Using cached attmap-0.13.2-py3-none-any.whl (12 kB)
Collecting attrs==22.2.0
  Using cached attrs-22.2.0-py3-none-any.whl (60 kB)
Requirement already satisfied: backports-functools-lru-cache==1.6.4 in /home/karenhn/.conda/envs/snakemake_mamba_old3/lib/python3.10/site-packages (from -r /scratch/karenhn/KOunt/condaenv.ij3k4slf.requirements.txt (line 9)) (1.6.4)
Collecting bcrypt==3.2.2
  Using cached bcrypt-3.2.2-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (62 kB)
Collecting boto3==1.26.77
  Using cached boto3-1.26.77-py3-none-any.whl (132 kB)
Collecting botocore==1.29.77
  Using cached botocore-1.29.77-py3-none-any.whl (10.4 MB)
Collecting brotlipy==0.7.0
  Using cached brotlipy-0.7.0-cp35-abi3-manylinux2010_x86_64.whl (1.1 MB)
Collecting cachetools==5.3.0
  Using cached cachetools-5.3.0-py3-none-any.whl (9.3 kB)
Collecting certifi==2022.12.7
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting cffi==1.15.1
  Using cached cffi-1.15.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (441 kB)
Collecting conda-package-handling
  Downloading conda_package_handling-2.4.0-py3-none-any.whl (22 kB)
Collecting conda-package-streaming==0.7.0
  Downloading conda_package_streaming-0.7.0-py3-none-any.whl (14 kB)
Collecting configargparse==1.5.3
  Downloading ConfigArgParse-1.5.3-py3-none-any.whl (20 kB)
Requirement already satisfied: connection-pool==0.0.3 in /home/karenhn/.conda/envs/snakemake_mamba_old3/lib/python3.10/site-packages (from -r /scratch/karenhn/KOunt/condaenv.ij3k4slf.requirements.txt (line 20)) (0.0.3)
Requirement already satisfied: cryptography==38.0.4 in /home/karenhn/.conda/envs/snakemake_mamba_old3/lib/python3.10/site-packages (from -r /scratch/karenhn/KOunt/condaenv.ij3k4slf.requirements.txt (line 21)) (38.0.4)
Requirement already satisfied: datrie==0.8.2 in /home/karenhn/.conda/envs/snakemake_mamba_old3/lib/python3.10/site-packages (from -r /scratch/karenhn/KOunt/condaenv.ij3k4slf.requirements.txt (line 22)) (0.8.2)
Collecting defusedxml==0.7.1
  Downloading defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting docutils==0.19
  Downloading docutils-0.19-py3-none-any.whl (570 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 570.5/570.5 kB 12.5 MB/s eta 0:00:00
Collecting dpath==2.1.4
  Downloading dpath-2.1.4-py3-none-any.whl (17 kB)
Collecting dropbox==11.36.0
  Downloading dropbox-11.36.0-py3-none-any.whl (594 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 594.0/594.0 kB 21.8 MB/s eta 0:00:00
Collecting exceptiongroup==1.1.0
  Downloading exceptiongroup-1.1.0-py3-none-any.whl (14 kB)
Requirement already satisfied: fastjsonschema==2.16.2 in /home/karenhn/.conda/envs/snakemake_mamba_old3/lib/python3.10/site-packages (from -r /scratch/karenhn/KOunt/condaenv.ij3k4slf.requirements.txt (line 28)) (2.16.2)
Collecting filechunkio
  Downloading filechunkio-1.8.tar.gz (2.3 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
                   failed
CondaEnvException: Pip failed
```

**Comment by jmattock5** [comment] 2024-10-17 12:58
Hi Karen,
No problem, happy to help :)

Please can you try running this command using the snakemake env that worked and this Snakefile
[Snakefile_trim.txt](https://github.com/user-attachments/files/17412650/Snakefile_trim.txt). I've edited it so it should only run the trim rule, it looks like Snakemake isn't waiting for rules to finish so I want to check that it can do just one rule.
```
snakemake -k --ri --cores 8 --snakefile Snakefile_trim.txt
```

Thanks,
Jenny

**Comment by karenhn** [comment] 2024-10-17 22:08
Hi Jenny, 

Nope, still missing the Touch files...

```
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 8
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job stats:
job      count    min threads    max threads
-----  -------  -------------  -------------
all          1              1              1
trim         1              1              1
total        2              1              1

Select jobs to execute...

[Fri Oct 18 10:30:29 2024]
rule trim:
    input: test_fastqs/ERR2027889_005/ERR2027889_005_R1.fastq.gz, test_fastqs/ERR2027889_005/ERR2027889_005_R2.fastq.gz
    output: out/Touch/trim_ERR2027889_005
    jobid: 1
    reason: Missing output files: out/Touch/trim_ERR2027889_005
    wildcards: id=ERR2027889_005
    resources: tmpdir=/tmp

/bin/bash: line 3: fastp: command not found
/bin/bash: line 8: fastq_info: command not found
read names not unique or fastqs invalid
Waiting at most 500 seconds for missing files.
MissingOutputException in rule trim in file /scratch/karenhn/KOunt/Snakefile_trim.txt, line 137:
Job 1  completed successfully, but some output files are missing. Missing files after 500 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
out/Touch/trim_ERR2027889_005
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-10-18T103027.875372.snakemake.log
```

Karen

**Comment by karenhn** [comment] 2024-10-21 00:09
Hi Jenny, 

This seems to be missing commands now as well as the out files.

Karen

```
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 8
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job stats:
job      count    min threads    max threads
-----  -------  -------------  -------------
all          1              1              1
trim         1              1              1
total        2              1              1

Select jobs to execute...

[Fri Oct 18 10:30:29 2024]
rule trim:
    input: test_fastqs/ERR2027889_005/ERR2027889_005_R1.fastq.gz, test_fastqs/ERR2027889_005/ERR2027889_005_R2.fastq.gz
    output: out/Touch/trim_ERR2027889_005
    jobid: 1
    reason: Missing output files: out/Touch/trim_ERR2027889_005
    wildcards: id=ERR2027889_005
    resources: tmpdir=/tmp

/bin/bash: line 3: fastp: command not found
/bin/bash: line 8: fastq_info: command not found
read names not unique or fastqs invalid
Waiting at most 500 seconds for missing files.
MissingOutputException in rule trim in file /scratch/karenhn/KOunt/Snakefile_trim.txt, line 137:
Job 1  completed successfully, but some output files are missing. Missing files after 500 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
out/Touch/trim_ERR2027889_005
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-10-18T103027.875372.snakemake.log
```

**Comment by jmattock5** [comment] 2024-10-21 15:49
Hi Karen,
It looks like snakemake cannot find the trim env and that the issue is with env installation on your system. Please could you do the following and then send me the messages you get, even if it looks like it's ran ok?
```
rm -r .snakemake
snakemake --conda-create-envs-only --cores 1 --use-conda --snakefile Snakefile_trim.txt
```
Thanks,
Jenny

**Comment by karenhn** [comment] 2024-10-22 02:02
Hi Jenny, 

Two options for you :)
First try I still had priority strict on:

```
Building DAG of jobs...
Creating conda environment envs/fastp_utils_KOunt.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /scratch/karenhn/KOunt/envs/fastp_utils_KOunt.yaml:
Command:
mamba env create --quiet --file "/scratch/karenhn/KOunt/.snakemake/conda/dbbaf8f0a796cc0634a3a5f0cc802561_.yaml" --prefix "/scratch/karenhn/KOunt/.snkemake/conda/dbbaf8f0a796cc0634a3a5f0cc802561_"
Output:
Retrieving notices: ...working... done
Encountered problems while solving:
  - package c-ares-1.18.1-h7f98852_0 is excluded by strict repo priority
  - package libdeflate-1.13-h166bdaf_0 is excluded by strict repo priority
```
Then tried again with `conda config --set channel_priority flexible `

```
Building DAG of jobs...
Your conda installation is not configured to use strict channel priorities. This is however crucial for having robust and correct environments (for details, see https://conda-forge.org/docs/user/tipsandtricks.html). Please consider to configure strict priorities by executing 'conda config --set channel_priority strict'.
Creating conda environment envs/fastp_utils_KOunt.yaml...
Downloading and installing remote packages.
Environment for /scratch/karenhn/KOunt/envs/fastp_utils_KOunt.yaml created (location: .snakemake/conda/dbbaf8f0a796cc0634a3a5f0cc802561_)
```

Karen

**Comment by jmattock5** [comment] 2024-10-22 13:11
Hi Karen,
It looks like the env you made with channel_priority flexible should work, good idea. Could you try ```snakemake -k --ri --cores 8 --snakefile Snakefile_trim.txt``` to see if it works now? Fingers crossed!
Jenny

**Comment by karenhn** [comment] 2024-10-22 20:29
Hi Jenny, 

Unfortunately it looks like I'm still having the same issues with missing files: 

```
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 8
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job stats:
job      count    min threads    max threads
-----  -------  -------------  -------------
all          1              1              1
trim         1              1              1
total        2              1              1

Select jobs to execute...

[Wed Oct 23 09:19:31 2024]
rule trim:
    input: test_fastqs/ERR2027889_005/ERR2027889_005_R1.fastq.gz, test_fastqs/ERR2027889_005/ERR2027889_005_R2.fastq.gz
    output: out/Touch/trim_ERR2027889_005
    jobid: 1
    reason: Missing output files: out/Touch/trim_ERR2027889_005
    wildcards: id=ERR2027889_005
    resources: tmpdir=/tmp

/bin/bash: line 3: fastp: command not found
/bin/bash: line 8: fastq_info: command not found
read names not unique or fastqs invalid
Waiting at most 500 seconds for missing files.
MissingOutputException in rule trim in file /scratch/karenhn/KOunt/Snakefile_trim.txt, line 137:
Job 1  completed successfully, but some output files are missing. Missing files after 500 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
out/Touch/trim_ERR2027889_005
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-10-23T091926.195692.snakemake.log
```

Karen

**Comment by jmattock5** [comment] 2024-10-23 12:22
Hi Karen,
How strange, your system can't find the trim env even though it was made correctly. Please could you make sure that the env in .snakemake/conda is the output of the successful env creation you posted about and then try running snakemake again with the addition of use-conda or specifying the env location:
```
snakemake -k --ri --cores 8 --snakefile Snakefile_trim.txt --use-conda --conda-prefix /scratch/karenhn/KOunt/.snakemake/conda/
```
Jenny

**Comment by karenhn** [comment] 2024-10-24 19:37
Hi Jenny, 

This seems to work! I checked the .snakemake/conda directory and had an env named dbbaf8f0a796cc0634a3a5f0cc802561_ (is this normal?), used that as the conda prefix and the log indicated it worked:

```
Building DAG of jobs...
Your conda installation is not configured to use strict channel priorities. This is however crucial for having robust and correct environments (for details, see https://conda-forge.org/docs/user/tipsandtricks.html). Please consider to configure strict priorities by executing 'conda config --set channel_priority strict'.
Creating conda environment envs/fastp_utils_KOunt.yaml...
Downloading and installing remote packages.
Environment for /scratch/karenhn/KOunt/envs/fastp_utils_KOunt.yaml created (location: .snakemake/conda/dbbaf8f0a796cc0634a3a5f0cc802561_/91c530d5331cefd4bf2373aca650c703_)
Using shell: /bin/bash
Provided cores: 8
Rules claiming more threads will be scaled down.
Job stats:
job      count    min threads    max threads
-----  -------  -------------  -------------
all          1              1              1
trim         1              1              1
total        2              1              1

Select jobs to execute...

[Thu Oct 24 08:36:11 2024]
rule trim:
    input: test_fastqs/ERR2027889_005/ERR2027889_005_R1.fastq.gz, test_fastqs/ERR2027889_005/ERR2027889_005_R2.fastq.gz
    output: out/Touch/trim_ERR2027889_005
    jobid: 1
    reason: Missing output files: out/Touch/trim_ERR2027889_005
    wildcards: id=ERR2027889_005
    resources: tmpdir=/tmp

Activating conda environment: .snakemake/conda/dbbaf8f0a796cc0634a3a5f0cc802561_/91c530d5331cefd4bf2373aca650c703_
[Thu Oct 24 08:36:51 2024]
Finished job 1.
1 of 2 steps (50%) done
Select jobs to execute...

[Thu Oct 24 08:36:51 2024]
localrule all:
    input: out/Touch/trim_ERR2027889_005
    jobid: 0
    reason: Input files updated by another job: out/Touch/trim_ERR2027889_005
    resources: tmpdir=/tmp

[Thu Oct 24 08:36:51 2024]
Finished job 0.
2 of 2 steps (100%) done
Complete log: .snakemake/log/2024-10-24T083337.785912.snakemake.log 
```

I then tried to do a full run with `snakemake -k --ri --cores 8 --use-conda --conda-prefix /scratch/karenhn/KOunt/.snakemake/conda/dbbaf8f0a796cc0634a3a5f0cc802561_` and it looks like this worked too,  I have multiple results directories and files in the out directory. There were some warnings on screen (`warning :chr ID :k87_176_ERR2027889_005 can't found in the chr2outfile List, will be assigned to the NaAss.bam`), although these don't appear to be in the full log file 
[2024-10-24T125000.719499.snakemake.log](https://github.com/user-attachments/files/17511880/2024-10-24T125000.719499.snakemake.log)

However, when I went back into .snakemake/conda I noticed the dbbaf8f0a796cc0634a3a5f0cc802561_ env directory now has a heap of other long name directories which also appear to be envs - e.g. \scratch\karenhn\KOunt\.snakemake\conda\dbbaf8f0a796cc0634a3a5f0cc802561_\ac1f1b55aa58da957455f6f794a8fa26_ also has bin, conda-meta, etc directories.  Is this normal? Are these meant to be created and confusingly named, or is this a result of me having to call the env name in the script?

Thanks. 
Karen

**Comment by jmattock5** [comment] 2024-10-28 09:03
Hi Karen,
Great, looks like we've solved the problem! 'dbbaf8f0a796cc0634a3a5f0cc802561_' is the env that snakemake made for the fastp environment so that is fine. As you specified that folder name in your full run trial snakemake has installed all the other envs into that directory. I'd advise you run only specifying the condo prefix '/scratch/karenhn/KOunt/.snakemake/conda' and it'll make each env into a separate directory. It looks like you might be able to name the directory what you want (it doesn't need to be in the hidden .snakemake folder) as long as you specify the condo prefix when the envs are made and the pipeline being run.

The warning 'warning :chr ID :k87_176_ERR2027889_005 can't found in the chr2outfile List, will be assigned to the NaAss.bam' is to be expected - these are contigs that haven't been annotated as proteins and are being filtered out as coverage is calculated.

Thanks,
Jenny

**Comment by karenhn** [comment] 2024-10-30 21:56
Perfect - thank you so much for all your help!
Karen

**Comment by jmattock5** [comment] 2024-10-31 13:03
No problem!  I'll close this issue now but please open another if you have any other problems.
Jenny

**Closed as completed by jmattock5** 2024-10-31 13:03 UTC
